ALTER TABLE `mt_coupon`
  ADD COLUMN `CONTENT` INT DEFAULT 1 NULL COMMENT '内容，如：1表示满减券、2表示折扣券' AFTER `TYPE`;
  
  CREATE TABLE `mt_upload_shipping_log` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `MERCHANT_ID` INT DEFAULT '0' COMMENT '所属商户ID',
  `STORE_ID` INT DEFAULT '0' COMMENT '所属店铺ID',
  `ORDER_ID` INT DEFAULT '0' COMMENT '订单ID',
  `ORDER_SN` VARCHAR(100) DEFAULT '' COMMENT '订单号',
  `MOBILE` VARCHAR(20) DEFAULT '' COMMENT '手机号',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  `OPERATOR` VARCHAR(30) DEFAULT NULL COMMENT '最后操作人',
  `STATUS` CHAR(1) DEFAULT 'A' COMMENT 'A：完成；B：失败',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='微信小程序上传发货信息记录表';
